[package]
name = "into-other"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "MIT"
repository = "https://github.com/jmesmon/into-other"
description = "An Into that isn't owned by From"
keywords = [ "convert", "into", "from" ]
